openapi: 3.0.3
info:
  title: Mastercard Developer Hub for FDX APIs FDX Authorization Server Application Check Controller Upload Data API
  version: 1.0.0
  description: Dynamic Client Registration, Token, Introspection, Authorize API
  contact:
    name: API Support
    email: apisupport@mastercard.com
    url: https://developer.mastercard.com/support
servers:
- url: http://localhost:8080
  description: Localhost URL
tags:
- name: Upload Data
  description: Upload accounts and transaction for user.
paths:
  /upload/addTransactions:
    post:
      tags:
      - Upload Data
      summary: Mastercard Developer Hub for FDX APIs add transactions details for user Id
      description: Return transactions response.
      operationId: addTransactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  accountCategory:
                    type: string
                    example: DEPOSIT_ACCOUNT
                  accountId:
                    type: string
                    example: '10002'
                  amount:
                    type: number
                    example: 0.01
                  checkNumber:
                    type: number
                    example: 45400222
                  debitCreditMemo:
                    type: string
                    example: CREDIT
                  description:
                    type: string
                    example: INTEREST PAYMENT
                  payee:
                    type: string
                    example: Test User
                  postedTimestamp:
                    type: string
                    example: '2019-07-31T12:00:00.000Z'
                  status:
                    type: string
                    example: POSTED
                  transactionId:
                    type: string
                    example: '12455'
                  transactionTimestamp:
                    type: string
                    example: '2019-07-31T12:00:00.000Z'
                  transactionType:
                    type: string
                    example: POSCREDIT
              example:
              - accountCategory: DEPOSIT_ACCOUNT
                accountId: '10002'
                amount: 0.01
                description: INTEREST PAYMENT
                postedTimestamp: '2019-07-31T12:00:00.000Z'
                status: POSTED
                transactionId: '12455'
                transactionTimestamp: '2019-07-31T12:00:00.000Z'
                transactionType: POSCREDIT
              - accountCategory: DEPOSIT_ACCOUNT
                accountId: '10002'
                amount: 0.03
                description: INTEREST PAYMENT
                postedTimestamp: '2019-02-28T12:00:00.000Z'
                status: POSTED
                transactionId: '45322'
                transactionTimestamp: '2019-02-28T12:00:00.000Z'
                transactionType: POSCREDIT
              - accountCategory: DEPOSIT_ACCOUNT
                accountId: '10002'
                amount: -300
                description: 'ALLY BANK TRANSFER WEB ID: 3770527921'
                postedTimestamp: '2019-02-26T12:00:00.000Z'
                status: POSTED
                transactionId: '4322777'
                transactionTimestamp: '2019-02-26T12:00:00.000Z'
                transactionType: POSDEBIT
              - accountCategory: DEPOSIT_ACCOUNT
                accountId: '10002'
                amount: 101.72
                checkNumber: 45400222
                debitCreditMemo: CREDIT
                description: VENMO CASHOUT
                payee: Test User
                postedTimestamp: '2019-02-26T12:00:00.000Z'
                status: POSTED
                transactionId: '5705141948'
                transactionTimestamp: '2019-02-26T12:00:00.000Z'
                transactionType: POSCREDIT
            examples:
              Add Transactions:
                value:
                - accountCategory: DEPOSIT_ACCOUNT
                  accountId: '10002'
                  amount: 0.01
                  description: INTEREST PAYMENT
                  postedTimestamp: '2019-07-31T12:00:00.000Z'
                  status: POSTED
                  transactionId: '12455'
                  transactionTimestamp: '2019-07-31T12:00:00.000Z'
                  transactionType: POSCREDIT
                - accountCategory: DEPOSIT_ACCOUNT
                  accountId: '10002'
                  amount: 0.03
                  description: INTEREST PAYMENT
                  postedTimestamp: '2019-02-28T12:00:00.000Z'
                  status: POSTED
                  transactionId: '45322'
                  transactionTimestamp: '2019-02-28T12:00:00.000Z'
                  transactionType: POSCREDIT
                - accountCategory: DEPOSIT_ACCOUNT
                  accountId: '10002'
                  amount: -300
                  description: 'ALLY BANK TRANSFER WEB ID: 3770527921'
                  postedTimestamp: '2019-02-26T12:00:00.000Z'
                  status: POSTED
                  transactionId: '4322777'
                  transactionTimestamp: '2019-02-26T12:00:00.000Z'
                  transactionType: POSDEBIT
                - accountCategory: DEPOSIT_ACCOUNT
                  accountId: '10002'
                  amount: 101.72
                  checkNumber: 45400222
                  debitCreditMemo: CREDIT
                  description: VENMO CASHOUT
                  payee: Test User
                  postedTimestamp: '2019-02-26T12:00:00.000Z'
                  status: POSTED
                  transactionId: '5705141948'
                  transactionTimestamp: '2019-02-26T12:00:00.000Z'
                  transactionType: POSCREDIT
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DataUploadResponsePojo'
  /upload/addAccount:
    post:
      tags:
      - Upload Data
      summary: Mastercard Developer Hub for FDX APIs add account for user Id
      description: Return accounts response.
      operationId: addAccount
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: string
        example: fdxUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  accountCategory:
                    type: string
                    example: DEPOSIT_ACCOUNT
                  accountId:
                    type: string
                    example: '10002'
                  accountNumber:
                    type: string
                    example: '7000003223'
                  accountNumberDisplay:
                    type: string
                    example: CHECKING
                  accountType:
                    type: string
                    example: CHECKING
                  annualPercentageYield:
                    type: number
                    example: 0.45
                  availableBalance:
                    type: number
                    example: 4984.46
                  balanceAsOf:
                    type: string
                    example: 2020-12-07T01:06:15.649-0500
                  balanceType:
                    type: string
                    example: ASSET
                  currency:
                    type: object
                    properties:
                      currencyCode:
                        type: string
                        example: USD
                      currencyRate:
                        nullable: true
                        example: null
                      originalCurrencyCode:
                        type: string
                        example: USD
                  currentBalance:
                    type: number
                    example: 4984.46
                  description:
                    type: string
                    example: My Checking Acc XXXX3223
                  displayName:
                    type: string
                    example: '******3223'
                  fiAttributes:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: interestPaidLastYear
                        value:
                          type: string
                          example: '14.08'
                    example:
                    - name: interestPaidLastYear
                      value: '14.08'
                    - name: interestPayoutFrequency
                      value: Annually (And At Maturity)
                  interestYtd:
                    type: number
                    example: 14.15
                  lastActivityDate:
                    type: string
                    example: 2020-11-09T00:00:00.000-0500
                  lineOfBusiness:
                    type: string
                    example: RETAIL
                  maturityDate:
                    type: string
                    example: 2020-11-09T00:00:00.000-0500
                  nickname:
                    type: string
                    example: My Checking Acc XXXX3223
                  openingDayBalance:
                    type: number
                    example: 500
                  productName:
                    type: string
                    example: Cash Management
                  routingTransitNumber:
                    type: string
                    example: '256074974'
                  status:
                    type: string
                    example: OPEN
                  transactionsIncluded:
                    type: boolean
                    example: false
              example:
              - accountCategory: DEPOSIT_ACCOUNT
                accountId: '10002'
                accountNumber: '7000003223'
                accountNumberDisplay: CHECKING
                accountType: CHECKING
                annualPercentageYield: 0.45
                availableBalance: 4984.46
                balanceAsOf: 2020-12-07T01:06:15.649-0500
                balanceType: ASSET
                currency:
                  currencyCode: USD
                  currencyRate: null
                  originalCurrencyCode: USD
                currentBalance: 4984.46
                description: My Checking Acc XXXX3223
                displayName: '******3223'
                fiAttributes:
                - name: interestPaidLastYear
                  value: '14.08'
                - name: interestPayoutFrequency
                  value: Annually (And At Maturity)
                interestYtd: 14.15
                lastActivityDate: 2020-11-09T00:00:00.000-0500
                lineOfBusiness: RETAIL
                maturityDate: 2020-11-09T00:00:00.000-0500
                nickname: My Checking Acc XXXX3223
                openingDayBalance: 500
                productName: Cash Management
                routingTransitNumber: '256074974'
                status: OPEN
                transactionsIncluded: false
            examples:
              Add accounts:
                value:
                - accountCategory: DEPOSIT_ACCOUNT
                  accountId: '10002'
                  accountNumber: '7000003223'
                  accountNumberDisplay: CHECKING
                  accountType: CHECKING
                  annualPercentageYield: 0.45
                  availableBalance: 4984.46
                  balanceAsOf: 2020-12-07T01:06:15.649-0500
                  balanceType: ASSET
                  currency:
                    currencyCode: USD
                    currencyRate: null
                    originalCurrencyCode: USD
                  currentBalance: 4984.46
                  description: My Checking Acc XXXX3223
                  displayName: '******3223'
                  fiAttributes:
                  - name: interestPaidLastYear
                    value: '14.08'
                  - name: interestPayoutFrequency
                    value: Annually (And At Maturity)
                  interestYtd: 14.15
                  lastActivityDate: 2020-11-09T00:00:00.000-0500
                  lineOfBusiness: RETAIL
                  maturityDate: 2020-11-09T00:00:00.000-0500
                  nickname: My Checking Acc XXXX3223
                  openingDayBalance: 500
                  productName: Cash Management
                  routingTransitNumber: '256074974'
                  status: OPEN
                  transactionsIncluded: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataUploadResponsePojo'
components:
  schemas:
    DataUploadResponsePojo:
      type: object
      properties:
        errorCode:
          type: integer
          description: This field indicate the error code of application
          format: int32
          readOnly: true
          example: 401
        error Message:
          type: string
          description: This field indicate the error message
          readOnly: true
          example: UNAUTHORIZED
        code:
          type: string
          description: This field indicate response code
          example: '200'
        message:
          type: string
          description: This field indicate response message
          example: SUCCESS
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
